import math
import torch
import torch.nn.functional as F

class MinMaxStats:
    """A class that holds the min-max values of the tree."""
    def __init__(self, known_bounds=None):
        self.maximum = known_bounds[1] if known_bounds else -float('inf')
        self.minimum = known_bounds[0] if known_bounds else float('inf')

    def update(self, value: float):
        self.maximum = max(self.maximum, value)
        self.minimum = min(self.minimum, value)

    def normalize(self, value: float) -> float:
        if self.maximum > self.minimum:
            return (value - self.minimum) / (self.maximum - self.minimum)
        return value

class Node:
    """MCTS Node representing a state generated by the dynamics model."""
    def __init__(self, prior: float):
        self.visit_count = 0
        self.to_play = -1
        self.prior = prior
        self.value_sum = 0
        self.children = {}
        self.hidden_state = None
        self.reward = 0

    def expanded(self) -> bool:
        return len(self.children) > 0

    def value(self) -> float:
        if self.visit_count == 0:
            return 0
        return self.value_sum / self.visit_count

class MCTS:
    """Monte-Carlo Tree Search configured for MuZero."""
    def __init__(self, dynamics_network, prediction_network, num_simulations=50, discount=0.99, pb_c_base=19652, pb_c_init=1.25):
        self.dynamics_network = dynamics_network
        self.prediction_network = prediction_network
        self.num_simulations = num_simulations
        self.discount = discount
        self.pb_c_base = pb_c_base
        self.pb_c_init = pb_c_init
        
    @torch.no_grad()
    def run(self, initial_hidden_state: torch.Tensor, min_max_stats: MinMaxStats, to_play: int = 1) -> Node:
        # Move inputs to CPU to iterate the loop or leave batched on GPU
        # For this single-env implementation, we expect shape (1, latent_dim)
        
        root = Node(0)
        root.hidden_state = initial_hidden_state
        root.to_play = to_play
        
        # Evaluate root
        policy_logits, value = self.prediction_network(initial_hidden_state)
        policy = F.softmax(policy_logits, dim=-1).squeeze(0).cpu().numpy()
        
        # Instantiate children based on prior policies
        for action, p in enumerate(policy):
            root.children[action] = Node(p)
            
        for _ in range(self.num_simulations):
            node = root
            search_path = [node]
            history = []
            
            # 1. Select
            while node.expanded():
                action, node = self.select_child(node, min_max_stats)
                search_path.append(node)
                history.append(action)
                
            # 2. Expand & Evaluate
            parent = search_path[-2]
            last_action = history[-1]
            
            # Form action tensor to pass natively to PyTorch dynamics
            # Reshape based on what your dynamics model expects 
            # (assuming flat action embedding or float equivalent here)
            action_tensor = torch.tensor([[last_action]], dtype=torch.float32, device=initial_hidden_state.device)
            
            next_hidden_state, reward = self.dynamics_network(parent.hidden_state, action_tensor)
            node.hidden_state = next_hidden_state
            node.reward = reward.item()
            
            policy_logits, value = self.prediction_network(next_hidden_state)
            policy = F.softmax(policy_logits, dim=-1).squeeze(0).cpu().numpy()
            value = value.item()
            
            for action, p in enumerate(policy):
                node.children[action] = Node(p)
                
            # 3. Backup
            self.backpropagate(search_path, value, min_max_stats)
            
        return root
        
    def select_child(self, node: Node, min_max_stats: MinMaxStats):
        best_action = None
        best_ucb = -float("inf")
        
        # PUCT formula
        for action, child in node.children.items():
            ucb = self.ucb_score(node, child, min_max_stats)
            if ucb > best_ucb:
                best_action = action
                best_ucb = ucb
                
        return best_action, node.children[best_action]
        
    def ucb_score(self, parent: Node, child: Node, min_max_stats: MinMaxStats) -> float:
        pb_c = math.log((parent.visit_count + self.pb_c_base + 1) / self.pb_c_base) + self.pb_c_init
        pb_c *= math.sqrt(parent.visit_count) / (child.visit_count + 1)
        prior_score = pb_c * child.prior
        
        if child.visit_count > 0:
            value_score = min_max_stats.normalize(child.reward + self.discount * child.value())
        else:
            value_score = 0
            
        return prior_score + value_score
        
    def backpropagate(self, search_path: list[Node], value: float, min_max_stats: MinMaxStats):
        for node in reversed(search_path):
            node.value_sum += value
            node.visit_count += 1
            min_max_stats.update(node.value())
            value = node.reward + self.discount * value
