from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


class TaskConditionedFastOperatorBank(nn.Module):
    """Task-conditioned fast operator network over a frozen CPPN-generated prior.

    The frozen v30/NEAT transport bank is treated as the base fast-network
    weights W0.  Each operator also owns a small globally learned low-rank
    residual, while a rule-conditioned hypernetwork generates an additional
    low-rank residual for each task.

        W(task, op) = W_cppn(op) + dW_static(op) + dW_fast(rule, op)

    The dynamic residual is intentionally low-rank.  This preserves the
    geometric bias of the evolved CPPN, keeps generation cheap, and gives each
    operator enough task-local plasticity to become a family of transformations
    instead of one rigid matrix.
    """

    def __init__(
        self,
        base_transport: torch.Tensor,
        base_scale: torch.Tensor,
        base_bias: torch.Tensor,
        rule_dim: int,
        operator_code_dim: int = 16,
        rank: int = 8,
        static_rank: int = 4,
        hidden_dim: int = 192,
        transport_delta_scale: float = 0.45,
        static_delta_scale: float = 0.20,
        feature_delta_scale: float = 0.10,
        delta_gate_init: float = -1.5,
        gate_max: float = 0.50,
        delta_rms_cap: float = 1.0,
    ):
        super().__init__()
        if base_transport.ndim != 3:
            raise ValueError("base_transport must have shape [K,N,N]")
        self.operator_count, self.n_slots, n2 = base_transport.shape
        if self.n_slots != n2:
            raise ValueError("base transport matrices must be square")

        self.rank = int(rank)
        self.static_rank = int(static_rank)
        self.transport_delta_scale = float(transport_delta_scale)
        self.static_delta_scale = float(static_delta_scale)
        self.feature_delta_scale = float(feature_delta_scale)
        self.gate_max = float(gate_max)
        self.delta_rms_cap = float(delta_rms_cap)

        # Frozen weights generated by the evolved CPPN.
        bt = base_transport.float().clamp_min(1e-8)
        bt = bt / bt.sum(dim=-1, keepdim=True).clamp_min(1e-8)
        self.register_buffer("base_transport", bt)
        self.register_buffer("base_log_transport", bt.log())
        self.register_buffer("base_scale", base_scale.float().clone())
        self.register_buffer("base_bias", base_bias.float().clone())

        self.operator_code = nn.Embedding(self.operator_count, operator_code_dim)

        # Globally learned residual retained from the previous ARC formulation.
        if self.static_rank > 0:
            self.static_u = nn.Parameter(torch.zeros(self.operator_count, self.n_slots, self.static_rank))
            self.static_v = nn.Parameter(torch.zeros(self.operator_count, self.n_slots, self.static_rank))
            nn.init.normal_(self.static_u, std=0.02)
            nn.init.normal_(self.static_v, std=0.02)
        else:
            self.register_parameter("static_u", None)
            self.register_parameter("static_v", None)

        # Task hypernetwork.  It does not emit a dense N x N matrix directly;
        # instead it emits node-wise low-rank factors U and V for each operator.
        context_dim = rule_dim + operator_code_dim
        self.context = nn.Sequential(
            nn.LayerNorm(context_dim),
            nn.Linear(context_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
        )
        self.fast_u_head = nn.Linear(hidden_dim, self.n_slots * self.rank)
        self.fast_v_head = nn.Linear(hidden_dim, self.n_slots * self.rank)

        # Dynamic feature-affine portion of the fast network.  Shapes are
        # inferred from the frozen base bank and flattened for generation.
        self.scale_shape = tuple(base_scale.shape[1:])
        self.bias_shape = tuple(base_bias.shape[1:])
        self.scale_numel = int(math.prod(self.scale_shape)) if self.scale_shape else 1
        self.bias_numel = int(math.prod(self.bias_shape)) if self.bias_shape else 1
        self.fast_scale_head = nn.Linear(hidden_dim, self.scale_numel)
        self.fast_bias_head = nn.Linear(hidden_dim, self.bias_numel)

        # DeltaNet-like write gate: the task embedding decides how strongly its
        # fast weights should overwrite/augment the evolved base computation.
        self.fast_gate_head = nn.Linear(hidden_dim, 1)
        nn.init.constant_(self.fast_gate_head.bias, delta_gate_init)

        # Keep the task-conditioned branch initially close to the CPPN prior.
        for head in (self.fast_u_head, self.fast_v_head, self.fast_scale_head, self.fast_bias_head):
            nn.init.normal_(head.weight, std=0.01)
            nn.init.zeros_(head.bias)

    def _contexts(self, rule: torch.Tensor) -> torch.Tensor:
        B = rule.shape[0]
        op_ids = torch.arange(self.operator_count, device=rule.device)
        op = self.operator_code(op_ids)[None].expand(B, -1, -1)
        r = rule[:, None, :].expand(-1, self.operator_count, -1)
        return self.context(torch.cat([r, op], dim=-1))

    def _static_transport_delta(self) -> torch.Tensor:
        if self.static_u is None:
            return torch.zeros_like(self.base_transport)
        return torch.einsum("kir,kjr->kij", self.static_u, self.static_v) / math.sqrt(max(self.static_rank, 1))

    def fast_parameters(self, rule: torch.Tensor):
        """Generate per-task/per-operator fast-network parameters."""
        B = rule.shape[0]
        ctx = self._contexts(rule)
        U = self.fast_u_head(ctx).view(B, self.operator_count, self.n_slots, self.rank)
        V = self.fast_v_head(ctx).view(B, self.operator_count, self.n_slots, self.rank)
        raw_delta = torch.einsum("bkir,bkjr->bkij", U, V) / math.sqrt(max(self.rank, 1))
        # Trust-region normalization: preserve tiny initial deltas, but prevent
        # the bilinear U/V factors from growing without bound and overwhelming
        # the evolved CPPN prior. Each task/operator matrix is capped by RMS.
        rms = raw_delta.pow(2).mean(dim=(-2, -1), keepdim=True).sqrt().clamp_min(1e-8)
        scale = torch.clamp(self.delta_rms_cap / rms, max=1.0)
        delta = raw_delta * scale
        gate = self.gate_max * torch.sigmoid(self.fast_gate_head(ctx)).view(B, self.operator_count, 1, 1)

        scale_delta = self.fast_scale_head(ctx)
        bias_delta = self.fast_bias_head(ctx)
        if self.scale_shape:
            scale_delta = scale_delta.view(B, self.operator_count, *self.scale_shape)
        else:
            scale_delta = scale_delta.view(B, self.operator_count)
        if self.bias_shape:
            bias_delta = bias_delta.view(B, self.operator_count, *self.bias_shape)
        else:
            bias_delta = bias_delta.view(B, self.operator_count)
        return delta, scale_delta, bias_delta, gate

    def transports(self, rule: torch.Tensor) -> torch.Tensor:
        dynamic, _, _, gate = self.fast_parameters(rule)
        static = self._static_transport_delta()[None]
        logits = (
            self.base_log_transport[None]
            + self.static_delta_scale * static
            + self.transport_delta_scale * gate * dynamic
        )
        return torch.softmax(logits, dim=-1)

    @staticmethod
    def _expand_feature_affine(x: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """Expand [K,...] or [B,K,...] feature terms for [B,K,N,D]."""
        if x.ndim == 1:          # [K]
            return x[None, :, None, None]
        if x.ndim == 2:
            if x.shape[0] == target.shape[0]:  # [B,K]
                return x[:, :, None, None]
            return x[None, :, None, :]          # [K,D]
        if x.ndim == 3:         # usually [B,K,D]
            return x[:, :, None, :]
        return x

    def apply_all(self, H: torch.Tensor, rule: torch.Tensor) -> torch.Tensor:
        """Apply all K task-conditioned fast operators. Returns [B,K,N,D]."""
        dynamic, scale_delta, bias_delta, gate = self.fast_parameters(rule)
        static = self._static_transport_delta()[None]
        logits = (
            self.base_log_transport[None]
            + self.static_delta_scale * static
            + self.transport_delta_scale * gate * dynamic
        )
        T = torch.softmax(logits, dim=-1)
        out = torch.einsum("bkij,bjd->bkid", T, H)

        base_scale = self._expand_feature_affine(self.base_scale, out)
        base_bias = self._expand_feature_affine(self.base_bias, out)
        dyn_scale = self._expand_feature_affine(scale_delta, out)
        dyn_bias = self._expand_feature_affine(bias_delta, out)
        feature_gate = gate
        while feature_gate.ndim < out.ndim:
            feature_gate = feature_gate.unsqueeze(-1)

        # Preserve the exact frozen affine at zero dynamic output.  Dynamic
        # scale uses tanh around multiplicative 1; dynamic bias is additive.
        scale = base_scale * (1.0 + self.feature_delta_scale * feature_gate * torch.tanh(dyn_scale))
        bias = base_bias + self.feature_delta_scale * feature_gate * torch.tanh(dyn_bias)
        return out * scale + bias

    def apply_selected(self, H: torch.Tensor, actions: torch.Tensor, rule: torch.Tensor) -> torch.Tensor:
        all_ops = self.apply_all(H, rule)
        b = torch.arange(H.shape[0], device=H.device)
        return all_ops[b, actions.long()]

    def trust_region(self, rule: torch.Tensor) -> dict[str, torch.Tensor]:
        """Differentiable distance from the evolved CPPN prior for a task batch."""
        dynamic, _, _, gate = self.fast_parameters(rule)
        static = self._static_transport_delta()[None]
        logits = (
            self.base_log_transport[None]
            + self.static_delta_scale * static
            + self.transport_delta_scale * gate * dynamic
        )
        T = torch.softmax(logits, dim=-1)
        base = self.base_transport[None].expand_as(T)
        kl = (T * (torch.log(T.clamp_min(1e-8)) - torch.log(base.clamp_min(1e-8)))).sum(dim=-1).mean()
        return {
            "transport_kl": kl,
            "gate_mean": gate.mean(),
            "delta_rms": dynamic.pow(2).mean().sqrt(),
        }

    def regularization(self) -> torch.Tensor:
        terms = []
        if self.static_u is not None:
            terms.extend([self.static_u.pow(2).mean(), self.static_v.pow(2).mean()])
        for p in (
            self.operator_code.weight,
            self.fast_u_head.weight,
            self.fast_v_head.weight,
            self.fast_scale_head.weight,
            self.fast_bias_head.weight,
        ):
            terms.append(p.pow(2).mean())
        return torch.stack(terms).mean()

    @torch.no_grad()
    def diagnostics(self, rule: torch.Tensor) -> dict[str, torch.Tensor]:
        dynamic, _, _, gate = self.fast_parameters(rule)
        trust = self.trust_region(rule)
        return {
            "fast_gate": gate.mean(),
            "fast_gate_max": gate.max(),
            "fast_delta_rms": dynamic.pow(2).mean().sqrt(),
            "transport_kl": trust["transport_kl"],
            "static_delta_rms": self._static_transport_delta().pow(2).mean().sqrt(),
        }
